<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMEwr63j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMEwr63j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMEwr63j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMEwr63j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMEwr63j\App_KernelDevDebugContainer([
    'container.build_hash' => 'MEwr63j',
    'container.build_id' => '131ec274',
    'container.build_time' => 1657964502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMEwr63j');
